# Generated by Django 4.1.3 on 2022-11-11 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contactNO', models.CharField(max_length=10)),
                ('emailID', models.EmailField(max_length=120)),
                ('age', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('context', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('desc', models.TextField(max_length=250)),
                ('price', models.FloatField(max_length=7)),
                ('duration', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('contactNo', models.CharField(max_length=10)),
                ('emailId', models.EmailField(max_length=125)),
                ('age', models.PositiveIntegerField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('joinDate', models.DateTimeField(auto_now=True)),
                ('expDate', models.DateTimeField(max_length=20)),
                ('totalAmount', models.FloatField(max_length=10)),
                ('initialAmount', models.FloatField(max_length=10)),
                ('dueAmount', models.FloatField(max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
            ],
        ),
    ]
