# Generated by Django 4.1.3 on 2022-11-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_enquiry_gender_alter_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(choices=[('O', 'Others'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('O', 'Others'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
